--{-# LANGUAGE NamedFieldPuns #-}
--{-# LANGUAGE OverloadedLabels #-}
--
module Messaging.Client.GTK.UI.ConversationBar where
----
----data ConversationBarEvent = 
----  NewEntry ConversationName
--  
--  
--import Data.Vector (Vector)
--import Messaging.Shared.Conversation
--
--data ConversationBarProps = ConversationBarProps 
--  { conversations :: Vector ConversationName
--  , focusedConversation :: ConversationName
--  }  
--  
--conversationBar :: Vector (Attribute Gtk.MenuBar ) -> MessageBoxProps -> Widget MessageBoxEvent
--conversationBar customAttributes customParams =
--  Widget $
--    CustomWidget
--      { customWidget,
--        customCreate,
--        customPatch,
--        customSubscribe,
--        customAttributes,
--        customParams
--      }
--  where
--    customWidget = Gtk.MenuBar