name:                messaging-client-core
version:             0.1.0.0
github:              "mheinzel/messaging"
license:             BSD3
author:              "Luciano Platjouw, Matthias Heinzel, Nathan Oerlemans, Bart Remmers"
maintainer:          "mheinzel@posteo.de"
copyright:           "2021 Luciano Platjouw, Matthias Heinzel, Nathan Oerlemans, Bart Remmers"

extra-source-files:
- README.md

synopsis:            Messaging client core functionality
category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/mheinzel/messaging#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- messaging-shared
- lens
- network
- text
- uri-bytestring
- vector
- websockets
- wuss

ghc-options:
- -Wall -Wincomplete-uni-patterns -Wincomplete-record-updates -Wpartial-fields -Wredundant-constraints

library:
  source-dirs: src
